---
apiVersion: v1
kind: Service
metadata:
  name: ambassador
  annotations:
    getambassador.io/config: |
      ---
      # /hello
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  helloworld_v1_mapping
      prefix: /
      service: helloworld-v1:5000
      host: helloworld.fyianlai.com
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  helloworld_v2_mapping
      prefix: /
      service: helloworld-v2:5000
      host: helloworld.fyianlai.com
      headers:
        x-helloworld-env: staging
spec:
  type: LoadBalancer
  ports:
   - port: 80
  selector:
    service: ambassador
